name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use OCaml 5.0.0
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 5.0.0
          dune-cache: true

      - name: Deploy odoc to GitHub Pages
        uses: ocaml/setup-ocaml/deploy-doc@v2
        with:
          destination-dir: dev
          enable-jekyll: true
